# Generated by Django 5.2.6 on 2025-09-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('Accountno', models.IntegerField(primary_key='Refno', serialize=False)),
                ('Address', models.CharField(max_length=30)),
                ('Aadharno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
